spring:
  application:
    name: resume-parser-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/resume

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083