spring:
  application:
    name: job-posting-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/job

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081

