server:
  port: 8080

spring:
  application:
    name: ui-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
